import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/public/sass/index.scss";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Team Chate Application",
	description: "Generated by create next app",
};

type LayoutProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en" className="">
			<body className={font.className}>{children}</body>
		</html>
	);
}
